spring.application.name=achat-fournisseur

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://ep-royal-tooth-abqcdkeq-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_VG1C9scxqkeN
spring.datasource.hikari.maximum-pool-size=2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect